CREATE TABLE Paises (
    PaisID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE Estados (
    EstadoID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL,
    PaisID INT,
    FOREIGN KEY (PaisID) REFERENCES Paises(PaisID)
);

CREATE TABLE Proveedores (
    ProveedorID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    RazonSocial VARCHAR(100),
    Domicilio_Calle VARCHAR(100),
    Domicilio_Numero VARCHAR(10),
    Domicilio_Colonia VARCHAR(100),
    Domicilio_CodigoPostal VARCHAR(10),
    Domicilio_EstadoID INT,
    Nombre VARCHAR(100),
    RFC VARCHAR(50),
    FOREIGN KEY (Domicilio_EstadoID) REFERENCES Estados(EstadoID)
);

CREATE TABLE ProveedorTelefonos (
    TelefonoID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ProveedorID INT,
    NumeroTelefono VARCHAR(20),
    TipoTelefono VARCHAR(50), -- Ejemplo: 'Móvil', 'Oficina', 'Fax', etc.
    FOREIGN KEY (ProveedorID) REFERENCES Proveedores(ProveedorID)
);

CREATE TABLE Empleados (
    EmpleadoID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100),
    ApellidoPaterno VARCHAR(100),
    ApellidoMaterno VARCHAR(100),
    FechaNacimiento DATE,
    FechaIngreso DATE
);

CREATE TABLE Clientes (
    ClienteID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100),
    ApellidoPaterno VARCHAR(100),
    ApellidoMaterno VARCHAR(100),
    Domicilio_Calle VARCHAR(100),
    Domicilio_Numero VARCHAR(10),
    Domicilio_Colonia VARCHAR(100),
    Domicilio_CodigoPostal VARCHAR(10),
    Domicilio_EstadoID INT,
    Email VARCHAR(100),
    RFC VARCHAR(50),
    FOREIGN KEY (Domicilio_EstadoID) REFERENCES Estados(EstadoID)
);

CREATE TABLE Categorias (
    CategoriaID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100),
    Descripcion TEXT
);

CREATE TABLE Productos (
    ProductoID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CodigoBarras VARCHAR(50),
    Nombre VARCHAR(100),
    PrecioCompra DECIMAL(10, 2),
    PrecioVenta DECIMAL(10, 2),
    Foto BYTEA,
    CantidadStock INT,
    CategoriaID INT,
    ProveedorID INT,
    FOREIGN KEY (CategoriaID) REFERENCES Categorias(CategoriaID),
    FOREIGN KEY (ProveedorID) REFERENCES Proveedores(ProveedorID)
);

CREATE TABLE Ventas (
    VentaID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Folio VARCHAR(20) UNIQUE,
    FechaVenta DATE,
    CantidadTotalPagar DECIMAL(10, 2),
    EmpleadoID INT,
    FOREIGN KEY (EmpleadoID) REFERENCES Empleados(EmpleadoID)
);

CREATE TABLE DetalleVenta (
    DetalleVentaID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    VentaID INT,
    ProductoID INT,
    CantidadProducto INT,
    PrecioTotalArticulo DECIMAL(10, 2),
    FOREIGN KEY (VentaID) REFERENCES Ventas(VentaID),
    FOREIGN KEY (ProductoID) REFERENCES Productos(ProductoID)
);

CREATE TABLE StockBajo (
    ProductoID INT PRIMARY KEY,
    EnBajoStock BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ProductoID) REFERENCES Productos(ProductoID)
);

CREATE TABLE ClienteEmails (
    ClienteID INT,
    Email VARCHAR(100),
    PRIMARY KEY (ClienteID, Email),
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID)
);
